[package]
name = "hp-bar-viewer"
version = "0.1.0"
authors = ["stringflow <Simon.oehmke@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.16.7"
termcolor = "1.1"
lazy_static = "1.4.0"
